certificates:
  '*.114514.plus':
    certificate: '-----BEGIN CERTIFICATE-----

      MIIFGTCCBAGgAwIBAgISBXwX+7mEoWc0ESQHIbSgBvg9MA0GCSqGSIb3DQEBCwUA

      MDMxCzAJBgNVBAYTAlVTMRYwFAYDVQQKEw1MZXQncyBFbmNyeXB0MQwwCgYDVQQD

      EwNSMTAwHhcNMjUwNDA4MjIyMzA0WhcNMjUwNzA3MjIyMzAzWjAYMRYwFAYDVQQD

      DA0qLjExNDUxNC5wbHVzMIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEA

      wsA6TEiuwlTuAk7B6NKp26MkG8QF2DAjyAFTOsYzvQ/dS0ugPCE5f1Frvf4AkOKq

      LeL305khuImYO1frpi/62G4xJHwJZ/2LGQgi+Bq+5yvlKr6yowcAYwHDQpXza9Rg

      e3ASMHTnmUHfKDnk/HMVTHBRF5eB49ZtGDzje67O7uIGvkl3c3/GO4lEpp/JAOym

      7BABMNXEDFVZEv+RGHLO6dxNAddO+cprxr8N6Rb1BXuYpLT/S03OJNk9N4Z52tl5

      MQW8R4Vwgm7D5kiAxhH2/58ACE0YUZEZfU1UPtTtDKRGijRM2j1sS6zeEKakkJt1

      Ybgl6Nrr+UA6lndjJtIbeQIDAQABo4ICQDCCAjwwDgYDVR0PAQH/BAQDAgWgMB0G

      A1UdJQQWMBQGCCsGAQUFBwMBBggrBgEFBQcDAjAMBgNVHRMBAf8EAjAAMB0GA1Ud

      DgQWBBSmWS7ewO2+R9ESZSSOeY4SDpr+6DAfBgNVHSMEGDAWgBS7vMNHpeS8qcbD

      pHIMEI2iNeHI6DBXBggrBgEFBQcBAQRLMEkwIgYIKwYBBQUHMAGGFmh0dHA6Ly9y

      MTAuby5sZW5jci5vcmcwIwYIKwYBBQUHMAKGF2h0dHA6Ly9yMTAuaS5sZW5jci5v

      cmcvMBgGA1UdEQQRMA+CDSouMTE0NTE0LnBsdXMwEwYDVR0gBAwwCjAIBgZngQwB

      AgEwLgYDVR0fBCcwJTAjoCGgH4YdaHR0cDovL3IxMC5jLmxlbmNyLm9yZy82Mi5j

      cmwwggEDBgorBgEEAdZ5AgQCBIH0BIHxAO8AdgDd3Mo0ldfhFgXnlTL6x5/4PRxQ

      39sAOhQSdgosrLvIKgAAAZYXtYZ8AAAEAwBHMEUCIDMXNBCcApHnAhqWcMVka5Bo

      7wlEMRGMK7Qx3JrPlNE9AiEArIg367PscN4YXAjAa62i0LWgCbyIYzZKQ06TiUG5

      kNYAdQCvGBoo1oyj4KmKTJxnqwn4u7wiuq68sTijoZ3T+bYDDQAAAZYXtYfPAAAE

      AwBGMEQCIB2fnbnpCeuVitMSbXK4RSsCuJvuVtvi/Blk6zYpRsnSAiASvXyUgWPU

      OUk2caI5ZmMWOXtORFqnN3uj6K54q4gFRzANBgkqhkiG9w0BAQsFAAOCAQEAtuan

      tLCZ5qp0PcI0T0U75EJlzeaF5YLXaYCYIP0r+JYa8I2qc6uJuehNPNTRf4RMcHzp

      abH2GB5dkHyKP8dEO1rqJoPndVCt3fNnCKeVqzdNA8xw5+ePqHOJcddRTabv/cNI

      ciEgKoup+oNBX4YWbxCSHhPzk2YSo6vER/+pyEO9I6MwoPCAuvV5/fqmKcbM7506

      PmCxcxU+Xs5SjQzKYP1SOP2zajgUngMn5ZZ4y01l+mlxKOKY/f6eJigt/e+tzqaD

      1y0PoU2mA+mG75HIBytu7fGKpcnQfh67OdS/noNML8hocyuSHpdi5CBK0fme98Zw

      B0jdvwWNCioNITwhMw==

      -----END CERTIFICATE-----


      -----BEGIN CERTIFICATE-----

      MIIFBTCCAu2gAwIBAgIQS6hSk/eaL6JzBkuoBI110DANBgkqhkiG9w0BAQsFADBP

      MQswCQYDVQQGEwJVUzEpMCcGA1UEChMgSW50ZXJuZXQgU2VjdXJpdHkgUmVzZWFy

      Y2ggR3JvdXAxFTATBgNVBAMTDElTUkcgUm9vdCBYMTAeFw0yNDAzMTMwMDAwMDBa

      Fw0yNzAzMTIyMzU5NTlaMDMxCzAJBgNVBAYTAlVTMRYwFAYDVQQKEw1MZXQncyBF

      bmNyeXB0MQwwCgYDVQQDEwNSMTAwggEiMA0GCSqGSIb3DQEBAQUAA4IBDwAwggEK

      AoIBAQDPV+XmxFQS7bRH/sknWHZGUCiMHT6I3wWd1bUYKb3dtVq/+vbOo76vACFL

      YlpaPAEvxVgD9on/jhFD68G14BQHlo9vH9fnuoE5CXVlt8KvGFs3Jijno/QHK20a

      /6tYvJWuQP/py1fEtVt/eA0YYbwX51TGu0mRzW4Y0YCF7qZlNrx06rxQTOr8IfM4

      FpOUurDTazgGzRYSespSdcitdrLCnF2YRVxvYXvGLe48E1KGAdlX5jgc3421H5KR

      mudKHMxFqHJV8LDmowfs/acbZp4/SItxhHFYyTr6717yW0QrPHTnj7JHwQdqzZq3

      DZb3EoEmUVQK7GH29/Xi8orIlQ2NAgMBAAGjgfgwgfUwDgYDVR0PAQH/BAQDAgGG

      MB0GA1UdJQQWMBQGCCsGAQUFBwMCBggrBgEFBQcDATASBgNVHRMBAf8ECDAGAQH/

      AgEAMB0GA1UdDgQWBBS7vMNHpeS8qcbDpHIMEI2iNeHI6DAfBgNVHSMEGDAWgBR5

      tFnme7bl5AFzgAiIyBpY9umbbjAyBggrBgEFBQcBAQQmMCQwIgYIKwYBBQUHMAKG

      Fmh0dHA6Ly94MS5pLmxlbmNyLm9yZy8wEwYDVR0gBAwwCjAIBgZngQwBAgEwJwYD

      VR0fBCAwHjAcoBqgGIYWaHR0cDovL3gxLmMubGVuY3Iub3JnLzANBgkqhkiG9w0B

      AQsFAAOCAgEAkrHnQTfreZ2B5s3iJeE6IOmQRJWjgVzPw139vaBw1bGWKCIL0vIo

      zwzn1OZDjCQiHcFCktEJr59L9MhwTyAWsVrdAfYf+B9haxQnsHKNY67u4s5Lzzfd

      u6PUzeetUK29v+PsPmI2cJkxp+iN3epi4hKu9ZzUPSwMqtCceb7qPVxEbpYxY1p9

      1n5PJKBLBX9eb9LU6l8zSxPWV7bK3lG4XaMJgnT9x3ies7msFtpKK5bDtotij/l0

      GaKeA97pb5uwD9KgWvaFXMIEt8jVTjLEvwRdvCn294GPDF08U8lAkIv7tghluaQh

      1QnlE4SEN4LOECj8dsIGJXpGUk3aU3KkJz9icKy+aUgA+2cP21uh6NcDIS3XyfaZ

      QjmDQ993ChII8SXWupQZVBiIpcWO4RqZk3lr7Bz5MUCwzDIA359e57SSq5CCkY0N

      4B6Vulk7LktfwrdGNVI5BsC9qqxSwSKgRJeZ9wygIaehbHFHFhcBaMDKpiZlBHyz

      rsnnlFXCb5s8HKn5LsUgGvB24L7sGNZP2CX7dhHov+YhD+jozLW2p9W4959Bz2Ei

      RmqDtmiXLnzqTpXbI+suyCsohKRg6Un0RC47+cpiVwHiXZAW+cn8eiNIjqbVgXLx

      KPpdzvvtTnOPlC7SQZSYmdunr3Bf9b77AiC/ZidstK36dRILKz7OA54=

      -----END CERTIFICATE-----'
    domain: '*.114514.plus'
    domains:
    - '*.114514.plus'
    last_updated: 2025-04-15 15:02:13.309946
    private_key: '-----BEGIN RSA PRIVATE KEY-----

      MIIEpAIBAAKCAQEAwsA6TEiuwlTuAk7B6NKp26MkG8QF2DAjyAFTOsYzvQ/dS0ug

      PCE5f1Frvf4AkOKqLeL305khuImYO1frpi/62G4xJHwJZ/2LGQgi+Bq+5yvlKr6y

      owcAYwHDQpXza9Rge3ASMHTnmUHfKDnk/HMVTHBRF5eB49ZtGDzje67O7uIGvkl3

      c3/GO4lEpp/JAOym7BABMNXEDFVZEv+RGHLO6dxNAddO+cprxr8N6Rb1BXuYpLT/

      S03OJNk9N4Z52tl5MQW8R4Vwgm7D5kiAxhH2/58ACE0YUZEZfU1UPtTtDKRGijRM

      2j1sS6zeEKakkJt1Ybgl6Nrr+UA6lndjJtIbeQIDAQABAoIBAQC9H2W9zNuBNm7H

      6OmgCmwPMfePyyWN0vn8cWT875sw36YcR728httKS6xgnbi4+pUe6ImYf93iUiR2

      hKQACBoGccPhVV7hELQyw9cJrxdycQskHnplnRgADacsE2iHb3+ef6/6RJzgFLr8

      WnSHv86QI4ZsbaIiuonI/uA+rPyht0X2YOHmkZgRy1LOqFtYbx1B4VzrakC5OKdh

      G/TWFAhXZvy4QVa0HMlS0zdV0paOHlJ5vWAxYgt/szT56RbwSq+8O1jnwP6fgCuq

      vj6v/NuF3KFj6hS2S2bPdkJpM4qMWFvnGQ9HxWutYrxDdSzmhxkbi2TYl0tSuq1Z

      eT7iUTGNAoGBAOIk7ddrz3vzNgs1vMIsA2SMQm6lIY94nPnQGkpUldCZ9VBZxU/4

      F8MKOCQcQuz/bHg7T+lZlDoz9OszYeNKf7K43Mr0KwUJMpCrLbGGfsu79ZNUTwdK

      jjaVVvyWl90zap5KEU4PXwdSWiiOHCb3HwYp4eyPWijj9AWEDa2bxLzbAoGBANx2

      SXJUTVDF7qMKxs4k8ZphlBSew/wexjwrpxHUZWBhpNl6tYMskCMGLPiO61HaSIxt

      DD8WMgWwQaqW/Fs4JOd8YhbCDAyVEC6RuGD332uYpbLmhkF0vi/MsJsdmfP8TiaK

      ijWikrn/OOsnAjaIRilB3eOju4Oc8TxMtS07iU87AoGBAKWTRFElrpSiTj+G6N2C

      PDmyODGq1helx8lghN9Hbyl8kBB0qfMTQtKa+N/3kUjU+yZMxwWjgNPclsZeqJ0y

      Pq0sjPxMKfNV+J/TtXD1eIDS7cshP3unKtjsHvRxjl929elPcbwlpP5HXZuz8QjW

      hvCMWc5KZ0jpHhGrzhf+pN1hAoGAPmJWfDywuCeaVJarFRBNMcNk9MTMbp6Ct+oe

      V6RDn5dh34yiqmDE1LRdq2Q94KalGt+MtJliREvQ+SXKeUGU59BBrXDxmengb10a

      0I2zsi26zbn/yavwWXRRkUM6GlmN/8f6Ph0n6ev3vksGjEnZmLkjwdPGLwMNHGQU

      bJ1JSJsCgYAzWWTkWEQo/gnCtC4Bg+z7najSOoDwQrsbJF84nxcA0B6kES3H1Yrr

      01D6+cSKVYXBxXnVzli/Pq3StQ68ENxNWUQLe9azgEpepf735axoluUsc46mghQM

      r8Y40W3aSVk+FyTaI9tPfNguEnVoxdFemrus7vhG8a+WWaWtaeDA4A==

      -----END RSA PRIVATE KEY-----'
  114514.plus:
    certificate: '-----BEGIN CERTIFICATE-----

      MIIFFjCCA/6gAwIBAgISBjTko2Wftyxxq3USmoDR3O5KMA0GCSqGSIb3DQEBCwUA

      MDMxCzAJBgNVBAYTAlVTMRYwFAYDVQQKEw1MZXQncyBFbmNyeXB0MQwwCgYDVQQD

      EwNSMTAwHhcNMjUwNDA4MjMyMDUwWhcNMjUwNzA3MjMyMDQ5WjAWMRQwEgYDVQQD

      EwsxMTQ1MTQucGx1czCCASIwDQYJKoZIhvcNAQEBBQADggEPADCCAQoCggEBAKjM

      DJJ3JSdRxlwQ74oWBNI2yGxzEnxyN5LYfvAteSJtdXaMvBOn7i50kKhTpT29F2fq

      wuCRVeRZKMUBSh39VmS5z1Sy80gaI050FkW+vd0979lhj64YKuSOYDdYaHkUOBwi

      J6voMW86Y2Ail/mgHgf2K9WUil6LJD/m32mBkI4NKpUj9Z2FjPRqkXxDxW3Y9J5V

      5SatQjdR57TafgKsp15CGNYqnYAdn/x5bDESd0sT2+dqd1wl1Si+fSqP0gPM8aPn

      kjm5z/cLT4fyVq1VDkOkKcRHxXnAVKG08XSkTwIUL4iIrMz0TDDplQ2VZsmkEaXS

      uY5DU3Yw+KMNYJCLKLMCAwEAAaOCAj8wggI7MA4GA1UdDwEB/wQEAwIFoDAdBgNV

      HSUEFjAUBggrBgEFBQcDAQYIKwYBBQUHAwIwDAYDVR0TAQH/BAIwADAdBgNVHQ4E

      FgQUeBce/5uHtBlBjdW1o7mAeBS13OwwHwYDVR0jBBgwFoAUu7zDR6XkvKnGw6Ry

      DBCNojXhyOgwVwYIKwYBBQUHAQEESzBJMCIGCCsGAQUFBzABhhZodHRwOi8vcjEw

      Lm8ubGVuY3Iub3JnMCMGCCsGAQUFBzAChhdodHRwOi8vcjEwLmkubGVuY3Iub3Jn

      LzAWBgNVHREEDzANggsxMTQ1MTQucGx1czATBgNVHSAEDDAKMAgGBmeBDAECATAu

      BgNVHR8EJzAlMCOgIaAfhh1odHRwOi8vcjEwLmMubGVuY3Iub3JnLzc1LmNybDCC

      AQQGCisGAQQB1nkCBAIEgfUEgfIA8AB1AKLjCuRF772tm3447Udnd1PXgluElNcr

      XhssxLlQpEfnAAABlhfqaacAAAQDAEYwRAIgYaxcBP4te3jvD8YNqG/GmScBBKW4

      8ro1RdzC6GP4+wQCIFA8HIE19iIZiMX+EnazfpXQhy/hIGVeDd42O/SXgVyiAHcA

      zPsPaoVxCWX+lZtTzumyfCLphVwNl422qX5UwP5MDbAAAAGWF+pxdAAABAMASDBG

      AiEA54EGzTTIqTSTOC4eLFdLDQmAc+CtU5WB4CtEuOzzcowCIQC8GHODVxNjS+ui

      Wmo6oanVJyor9yoR8ZF0JwmkCIr21TANBgkqhkiG9w0BAQsFAAOCAQEAv/M7LCO1

      +yqjWsj/Cg0/ZYwB95QQrFESKnvijx2Dxdv64MrZ0f44YjrM2i97kklFRMXe2V3B

      dWB/1R90SGjNUqzVlf6W1ZEbQXGYpnj/xgIh7j3uxOPDWc7TyWa+kr5VvRNjELgm

      VQv+g6xFizhs30pa1Ov37uzFflE4aTIeNnD6Ncjq+xAlvJYdJ4ES8LcyYQnqBun7

      D9DkTF629BzIrRPO6xWhpWk8QG5T1g6eSTZjaWIOPNP9KUFz94FDg6pgNzUX5tXc

      iJtWFC0fvLlp6x8WlDJIM1Q1bAub8bHOmtOrR8p0lO0VD0y6+VKRqXH0Bc3ku28s

      3GAeJiYlR2CJrw==

      -----END CERTIFICATE-----


      -----BEGIN CERTIFICATE-----

      MIIFBTCCAu2gAwIBAgIQS6hSk/eaL6JzBkuoBI110DANBgkqhkiG9w0BAQsFADBP

      MQswCQYDVQQGEwJVUzEpMCcGA1UEChMgSW50ZXJuZXQgU2VjdXJpdHkgUmVzZWFy

      Y2ggR3JvdXAxFTATBgNVBAMTDElTUkcgUm9vdCBYMTAeFw0yNDAzMTMwMDAwMDBa

      Fw0yNzAzMTIyMzU5NTlaMDMxCzAJBgNVBAYTAlVTMRYwFAYDVQQKEw1MZXQncyBF

      bmNyeXB0MQwwCgYDVQQDEwNSMTAwggEiMA0GCSqGSIb3DQEBAQUAA4IBDwAwggEK

      AoIBAQDPV+XmxFQS7bRH/sknWHZGUCiMHT6I3wWd1bUYKb3dtVq/+vbOo76vACFL

      YlpaPAEvxVgD9on/jhFD68G14BQHlo9vH9fnuoE5CXVlt8KvGFs3Jijno/QHK20a

      /6tYvJWuQP/py1fEtVt/eA0YYbwX51TGu0mRzW4Y0YCF7qZlNrx06rxQTOr8IfM4

      FpOUurDTazgGzRYSespSdcitdrLCnF2YRVxvYXvGLe48E1KGAdlX5jgc3421H5KR

      mudKHMxFqHJV8LDmowfs/acbZp4/SItxhHFYyTr6717yW0QrPHTnj7JHwQdqzZq3

      DZb3EoEmUVQK7GH29/Xi8orIlQ2NAgMBAAGjgfgwgfUwDgYDVR0PAQH/BAQDAgGG

      MB0GA1UdJQQWMBQGCCsGAQUFBwMCBggrBgEFBQcDATASBgNVHRMBAf8ECDAGAQH/

      AgEAMB0GA1UdDgQWBBS7vMNHpeS8qcbDpHIMEI2iNeHI6DAfBgNVHSMEGDAWgBR5

      tFnme7bl5AFzgAiIyBpY9umbbjAyBggrBgEFBQcBAQQmMCQwIgYIKwYBBQUHMAKG

      Fmh0dHA6Ly94MS5pLmxlbmNyLm9yZy8wEwYDVR0gBAwwCjAIBgZngQwBAgEwJwYD

      VR0fBCAwHjAcoBqgGIYWaHR0cDovL3gxLmMubGVuY3Iub3JnLzANBgkqhkiG9w0B

      AQsFAAOCAgEAkrHnQTfreZ2B5s3iJeE6IOmQRJWjgVzPw139vaBw1bGWKCIL0vIo

      zwzn1OZDjCQiHcFCktEJr59L9MhwTyAWsVrdAfYf+B9haxQnsHKNY67u4s5Lzzfd

      u6PUzeetUK29v+PsPmI2cJkxp+iN3epi4hKu9ZzUPSwMqtCceb7qPVxEbpYxY1p9

      1n5PJKBLBX9eb9LU6l8zSxPWV7bK3lG4XaMJgnT9x3ies7msFtpKK5bDtotij/l0

      GaKeA97pb5uwD9KgWvaFXMIEt8jVTjLEvwRdvCn294GPDF08U8lAkIv7tghluaQh

      1QnlE4SEN4LOECj8dsIGJXpGUk3aU3KkJz9icKy+aUgA+2cP21uh6NcDIS3XyfaZ

      QjmDQ993ChII8SXWupQZVBiIpcWO4RqZk3lr7Bz5MUCwzDIA359e57SSq5CCkY0N

      4B6Vulk7LktfwrdGNVI5BsC9qqxSwSKgRJeZ9wygIaehbHFHFhcBaMDKpiZlBHyz

      rsnnlFXCb5s8HKn5LsUgGvB24L7sGNZP2CX7dhHov+YhD+jozLW2p9W4959Bz2Ei

      RmqDtmiXLnzqTpXbI+suyCsohKRg6Un0RC47+cpiVwHiXZAW+cn8eiNIjqbVgXLx

      KPpdzvvtTnOPlC7SQZSYmdunr3Bf9b77AiC/ZidstK36dRILKz7OA54=

      -----END CERTIFICATE-----'
    domain: 114514.plus
    domains:
    - 114514.plus
    last_updated: 2025-04-15 14:48:41.571615
    private_key: '-----BEGIN RSA PRIVATE KEY-----

      MIIEpgIBAAKCAQEAqMwMknclJ1HGXBDvihYE0jbIbHMSfHI3kth+8C15Im11doy8

      E6fuLnSQqFOlPb0XZ+rC4JFV5FkoxQFKHf1WZLnPVLLzSBojTnQWRb693T3v2WGP

      rhgq5I5gN1hoeRQ4HCInq+gxbzpjYCKX+aAeB/Yr1ZSKXoskP+bfaYGQjg0qlSP1

      nYWM9GqRfEPFbdj0nlXlJq1CN1HntNp+AqynXkIY1iqdgB2f/HlsMRJ3SxPb52p3

      XCXVKL59Ko/SA8zxo+eSObnP9wtPh/JWrVUOQ6QpxEfFecBUobTxdKRPAhQviIis

      zPRMMOmVDZVmyaQRpdK5jkNTdjD4ow1gkIsoswIDAQABAoIBAQCgS4X04ShrOoEA

      lSSlIVvatSOHuY9olp6n2OhS9Rv/0aqmtec1U1ggzZlCAIz/ID7F9G60C9BhVToe

      O6dC633LkZiOepIFeqzkp+EuwoBTRaor6TYkwdaZzYsZg99SfBz8uoKqAYpQckZE

      2RUxfRiHvwLJhJISTlhSRtEKxHueKN/iMZKiK/Gn1jA8ZYhJRuARgtB11/Vk/L59

      NuoNI9SejG8BEoSvoAFy2jprNTeINnV61gGcEkYnx8M0XylEZ/Q+zXakvBHSdglO

      acaEsrLfejy3RHgialbrON9Wo+W2dYCDP+8tECjmrYndm3xemFyhB/1baQcAGWGK

      +fh3LnGhAoGBAM9LkJPC+XdCANJNJl3dyUU/inS2ar+tT4qhuHPIxMIfgRlNHHAg

      opeVVlwMos1nXKrwXvG9UBRD9nc05o8Cl6/1MR8db6Z438R9K6LuFLym74449IRJ

      BSZYPqARTJ1vtnEGajpAzDDKhlZgMNKuRDG8e9kPUD4QaLxnZrQyFojXAoGBANB0

      5EwSAFiMY8HnmcYTmBAEPT1uEdwsgvuUZv/kpwuFy7gv0mDDz6pLJqDUGGIMMxAN

      fVykh0LZ9qgbuY93Rfh8aEXrj0oHB+fjKPEw0yKYdLfFsoXa+1gOVEPdg093XoWP

      Q3D/K1tTmqyn8POgnKg17YgkoGDdetTOCjPss1eFAoGBAMu5X+VYAQQLgfMsj0BA

      78V2pQP/IvotwbZlKXnhHj4J6D6NYh1wdVq0EaN1Z6qmopP8l9LMUx8Xi+mru8tg

      qOLs/dGuhEP/FytsOK5vfUHKbjRAFU7M1JrSrvlxBvLTD2IVA+EsPYDWCSBqeJEV

      Yz/eFXlFa38TcVt345/EehERAoGBAJOERRL4IjqHjwjnhtC/iPq8pUHVpNn0vfSf

      PoyUGQp0cogzf2Nu7oSKjhl+PosUKwaPJUnsPLQ4Xu70P8qhE2kXUQs5+brfYt7c

      yFp2vNNcpCxwwTcsknXsHgGwvn378W3+xjEuwlXswiaw6jjeTj5Te3a+xKgH1CbI

      cDvyo6+pAoGBAKTcX8bXLPBYNZmoZsHeobB+Ny9veathGBJFnB7rVsdvYcjm65RP

      YnzNK/DvPCXVLD/b840Cf4Rvzx9l7oz1MgJKEccX4A7v3g3/2/ST2f/azQOA/3gH

      cp96u6vvxywd5wqOSsCiC238J75gjjA8GwPaVQnWleR4CF5MpyDRzn/J

      -----END RSA PRIVATE KEY-----'
synology:
  create_cert: false
  device_name: CertRenewal
  disable_cert_verify: true
  hostname: 100.111.0.111
  password: Qq159357123.
  port: 5001
  scheme: https
  username: jkfujr
webhook:
  enabled: true
  path: /webhook
  port: 18102
